#' Include additional postprocessing steps for
#' simulation
#'
#' Allow additional postprocessing steps to be
#' included in generate(), rather than running
#' after generate()
#'
#' Often it is more computationally efficient,
#' especially when parallel processing, to save
#' only key results from each simulation rather
#' than all the data, fit objects, etc.  This
#' function, run immediately after
#' \code{\link{blueprint}} or \code{\link{meta}},
#' allows additional postprocessing steps to be
#' specified afterwards and thereby included in
#' the simulation as it proceeds incrementally.
#'
#' Arbitrary R operations are not supported for
#' these postprocessing steps; only the
#' postprocessing steps included in the simpr
#' package (\code{\link{fit}},
#' \code{\link{tidy_fits}},
#' \code{\link{glance_fits}}).
#'
#' @param obj a \code{simpr_meta} object generated
#'   by \code{\link{meta}} or a
#'   \code{simpr_blueprint} object generated by
#'   \code{\link{meta}}
#' @return a \code{simpr_include} object.  This
#'   can be treated like a \code{simpr_tibble}
#'   object for the purposes of the supported
#'   functions (see Details).
#' @export
include = function(obj) {
  UseMethod("include")
}

create_include = function(obj) {
  if(!("simpr_include" %in% class(obj)))
    class(obj) = c("simpr_include", class(obj))

  return(obj)
}

#' @export
include.simpr_spec = function(obj) {
  create_include(obj)
}

#' @export
include.simpr_tibble = function(obj) {
  stop("`generate()` has already been run on this object. The `include()` function is only run before running `generate()`.")
}

# This adds a call (e.g. a simpr verb such as
# fit()) to the include_calls element
add_call = function(obj, obj_call, call_name, replace_arg = 2) {
  ## add the name of the function to be called
  obj_call[1] = call(call_name)

  ## replace the appropriate argument with "." for
  ## later piping. This is not necessary if this
  ## was originally generated from a pipe, but is
  ## necessary in case the function was NOT piped.
  obj_call[replace_arg] = call(".")

  obj$include_calls = c(obj$include_calls, obj_call)

  create_include(obj)
}



