#' Include additional postprocessing steps for
#' simulation
#'
#' Allow additional postprocessing steps to be
#' included in produce(), rather than running
#' after produce()
#'
#' Often it is more computationally efficient,
#' especially when parallel processing, to save
#' only key results from each simulation rather
#' than all the data, fit objects, etc.  This
#' function, run immediately after
#' \code{\link{blueprint}} or \code{\link{meta}},
#' allows additional postprocessing steps to be
#' specified afterwards and thereby included in
#' the simulation as it proceeds incrementally.
#'
#' Arbitrary R operations are not supported for
#' these postprocessing steps; only the
#' postprocessing steps included in the simpr
#' package (\code{\link{fit}},
#' \code{\link{tidy_fits}},
#' \code{\link{glance_fits}}) and some basic
#' \code{dplyr} verbs (\code{\link{mutate}},
#' \code{\link{filter}}, \code{\link{summarize}},
#' and \code{\link{select}}).
#'
#' @param obj a \code{simpr_meta} object generated
#'   by \code{\link{meta}} or a
#'   \code{simpr_blueprint} object generated by
#'   \code{\link{meta}}
#' @return a \code{simpr_include} object.  This
#'   can be treated like a \code{simpr_produce}
#'   object for the purposes of the supported
#'   functions (see Details).
include = function(obj) {
  UseMethod("include")
}

create_include = function(obj) {
  attributes(obj) = c(attributes(obj), list(include_class = class(obj)))
  class(obj) = "simpr_include"
  obj
}

#' @export
include.simpr_meta = function(obj) {
  create_include(obj)
}

#' @export
include.simpr_blueprint = function(obj) {
  create_include(obj)
}

#' @export
include.simpr_produce = function(obj) {
  stop("`produce()` has already been run on this object. The `include()` function is only run before running `produce()`.")
}



